    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Acre', 'Norte', 894470, 'Rio Branco', 152581)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Alagoas', 'Nordeste', 2696091, 'Maceió', 27768)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Amapá', 'Norte', 877613, 'Macapá', 142815)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Amazonas', 'Norte', 4102183, 'Manaus', 1571000)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Bahia', 'Nordeste', 5188787, 'Salvador', 567295)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Ceará', 'Nordeste', 9204435, 'Fortaleza', 148886)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Espírito Santo', 'Sudeste', 3885173, 'Vitória', 46095)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Goiás', 'Centro_Oeste', 7209483, 'Goiânia', 340086)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Maranhão', 'Nordeste', 7153262, 'São Luís', 331983)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Mato Grosso', 'Centro_Oeste', 3567234, 'Cuiabá', 903357)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Mato Grosso do Sul', 'Centro_Oeste', 2839156, 'Campo Grande', 357145)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Minas Gerais', 'Sudeste', 20870483, 'Belo Horizonte', 586528)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Pará', 'Norte', 8305359, 'Belém', 1248000)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Paraíba', 'Nordeste', 3994153, 'João Pessoa', 56467)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Paraná', 'Sul', 11080137, 'Curitiba', 199315)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Pernambuco', 'Nordeste', 9278183, 'Recife', 98312)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Piauí', 'Nordeste', 3281290, 'Teresina', 251529)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Rio de Janeiro', 'Sudeste', 16461789, 'Rio de Janeiro', 43696)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Rio Grande do Norte', 'Nordeste', 3409123, 'Natal', 52797)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Rio Grande do Sul', 'Sul', 11294138, 'Porto Alegre', 281748)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Rondônia', 'Centro_Oeste', 1749456, 'Porto Velho', 237576)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Roraima', 'Norte', 496936, 'Boa Vista', 223645)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Santa Catarina', 'Sul', 7338473, 'Florianópolis', 95346)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('São Paulo', 'Sudeste', 45140123, 'São Paulo', 248209)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Sergipe', 'Nordeste', 2221437, 'Aracaju', 21910)
    INSERT INTO ESTADO(`nome`, `regiao`, `populacao`, `capital`, `area`)
    VALUES('Tocantins', 'Nordeste', 1497346, 'Palmas', 277621)